typography_spectrum: 0.04241497744806111
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.6299267953727394
  lightness: 0.3490008593071252
  saturation: 0.6256934117991477
  rhythmicContrast: 0.2262335375417024
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3003908498212695
analytics:
  google: null
  facebook: null
  twitter: null
name: Core Process Psycotherapy
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Core Process Psychotherapy
description: a whole person approach
purpose: []
