typography_spectrum: 0.34609020920470357
color:
  brandColors:
    - '#6694C6'
    - '#608EC0'
    - '#5587BA'
    - '#5280B4'
    - '#4A78AC'
  brandStrength: 0.17487982008606195
  lightness: 0.9242014451883733
  saturation: 0.2719851213041693
  rhythmicContrast: 0.9212585578206927
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3003908498212695
analytics:
  google: null
  facebook: null
  twitter: null
name: Core Process Psycotherapy
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Appointments
    id: 3ada9445-7f84-4f88-a441-fd293120bc09
    type: content
favicon: null
title: Core Process Psychotherapy
description: a whole person approach
purpose: []
