layout_spectrum: 0.3181911944411695
typography_spectrum: 0.7436756961978972
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.41441149124875665
  lightness: 0.8040226853918284
  saturation: 0.5245270330924541
  rhythmicContrast: 0.33255672827363014
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Core Process Psycotherapy
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Who is psychotherapy for?
    id: 1dee3722-5e6c-4f70-8b74-76266d2c62d4
    type: content
  - name: About Core Process
    id: 26ac9968-2783-4b91-873c-03ec3f3bec3a
    type: content
  - name: Contact
    id: c2626c16-239f-44b4-9f12-9ef6c98a8dd0
    type: content
  - name: Courses & Events
    id: 0e0a02b7-d1ec-426b-8b24-73fa385e3a78
    type: content
  - name: In crisis?
    id: 36271eec-6bc7-4c96-a0df-54587e110544
    type: content
favicon: null
title: ''
description: ''
purpose: []
