layout_spectrum: 0.5958758860360831
typography_spectrum: 0.379510089289397
color:
  brandColors:
    - '#00276C'
    - '#D5E7FB'
    - '#FEFFFF'
    - '#1B67B3'
    - '#83A6C4'
  brandStrength: 0.7255105867516249
  lightness: 0.12390988715924323
  saturation: 0.14125405391678214
  rhythmicContrast: 0.782598664984107
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Core Process Psycotherapy
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Appointments
    id: 3ada9445-7f84-4f88-a441-fd293120bc09
    type: content
  - name: Training
    id: 8df314b3-ada0-48d8-9096-89b5bdb5fad6
    type: content
favicon: null
title: Core Process Psychotherapy
description: a whole person approach
purpose: []
