typography_spectrum: 0.5062451220583171
color:
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  brandStrength: 0.6504702756647021
  lightness: 0.057828051038086414
  saturation: 0.5933591481298208
  rhythmicContrast: 0.175390639109537
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.46541100228205323
analytics:
  google: null
  facebook: null
  twitter: null
name: Core Process Psycotherapy
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Core Process Psychotherapy
description: a whole person approach
purpose: []
