name: Core Process Psycotherapy
favicon: null
layout_spectrum: 0.17493
typography_spectrum: 0.33203
title: Core Process Psychotherapy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbffff'
    - '#395121'
    - '#93a364'
    - '#c7c7a3'
    - '#d0ff33'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
