typography_spectrum: 0.3166350240353495
color:
  brandColors:
    - '#0134A1'
    - '#015BCD'
    - '#9AE8FE'
    - '#4ABDFE'
    - '#E8FDFF'
  brandStrength: 0.6940054302103817
  lightness: 0.9115046984516084
  saturation: 0.5183199781458825
  rhythmicContrast: 0.3899276200681925
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.13702271087095141
analytics:
  google: null
  facebook: null
  twitter: null
name: Core Process Psycotherapy
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Core Process Psychotherapy
description: a whole person approach
purpose: []
