name: Core Process Psycotherapy
favicon: null
layout_spectrum: 0.76732
typography_spectrum: 0.33183
title: Core Process Psychotherapy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060b0f'
    - '#292e32'
    - '#f8f9fe'
    - '#8b7e78'
    - '#b29f8f'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
