typography_spectrum: 0.34609020920470357
color:
  brandColors:
    - '#6694C6'
    - '#608EC0'
    - '#5587BA'
    - '#5280B4'
    - '#4A78AC'
  brandStrength: 0.17487982008606195
  lightness: 0.9242014451883733
  saturation: 0.2719851213041693
  rhythmicContrast: 0.9212585578206927
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3003908498212695
analytics:
  google: null
  facebook: null
  twitter: null
name: Core Process Psycotherapy
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Core Process
    id: 26ac9968-2783-4b91-873c-03ec3f3bec3a
    type: content
  - name: Appointments
    id: 3ada9445-7f84-4f88-a441-fd293120bc09
    type: content
  - name: Who is psychotherapy for?
    id: 1dee3722-5e6c-4f70-8b74-76266d2c62d4
    type: content
  - name: Training
    id: 785dffcb-9de9-446e-99df-1f1e0cc8cbde
    type: content
favicon: null
title: Core Process Psychotherapy
description: a whole person approach
purpose: []
