typography_spectrum: 0.3657793046440929
color:
  brandColors:
    - '#00276C'
    - '#D5E7FB'
    - '#FEFFFF'
    - '#1B67B3'
    - '#83A6C4'
  brandStrength: 0.9029872494284064
  lightness: 0.9133005398325622
  saturation: 0.03950059483759105
  rhythmicContrast: 0.2513943014200777
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3567618876695633
analytics:
  google: null
  facebook: null
  twitter: null
name: Core Process Psycotherapy
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Who is psychotherapy for?
    id: 1dee3722-5e6c-4f70-8b74-76266d2c62d4
    type: content
  - name: About Core Process
    id: 26ac9968-2783-4b91-873c-03ec3f3bec3a
    type: content
  - name: Courses
    id: 0e0a02b7-d1ec-426b-8b24-73fa385e3a78
    type: content
  - name: In crisis?
    id: 36271eec-6bc7-4c96-a0df-54587e110544
    type: content
  - name: Contact
    id: c2626c16-239f-44b4-9f12-9ef6c98a8dd0
    type: content
favicon: null
title: Core Process Psychotherapy
description: a whole person approach
purpose: []
