typography_spectrum: 0.83641
color:
  brandColors:
    - '#060b0f'
    - '#292e32'
    - '#f8f9fe'
    - '#8b7e78'
    - '#b29f8f'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.335
analytics:
  google: null
  facebook: null
  twitter: null
name: Core Process Psycotherapy
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: a whole person approach
description: a whole person approach
purpose: []
