typography_spectrum: 0.9598050524946302
color:
  brandColors:
    - '#0134A1'
    - '#015BCD'
    - '#9AE8FE'
    - '#4ABDFE'
    - '#E8FDFF'
  brandStrength: 0.22948087612167
  lightness: 0.7330815193708986
  saturation: 0.4595303505193442
  rhythmicContrast: 0.31902813585475087
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3003908498212695
analytics:
  google: null
  facebook: null
  twitter: null
name: Core Process Psycotherapy
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Appointments
    id: 3ada9445-7f84-4f88-a441-fd293120bc09
    type: content
favicon: null
title: Core Process Psychotherapy
description: a whole person approach
purpose: []
