typography_spectrum: 0.3657793046440929
color:
  brandColors:
    - '#00276C'
    - '#D5E7FB'
    - '#FEFFFF'
    - '#1B67B3'
    - '#83A6C4'
  brandStrength: 0.9029872494284064
  lightness: 0.9133005398325622
  saturation: 0.03950059483759105
  rhythmicContrast: 0.2513943014200777
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3567618876695633
analytics:
  google: null
  facebook: null
  twitter: null
name: Core Process Psycotherapy
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Appointments
    id: 3ada9445-7f84-4f88-a441-fd293120bc09
    type: content
favicon: null
title: Core Process Psychotherapy
description: a whole person approach
purpose: []
