name: Core Process Psycotherapy
favicon: null
layout_spectrum: 0.7136215877253562
typography_spectrum: 0.54012
title: Core Process Psychotherapy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefdff'
    - '#964b72'
    - '#1d2a21'
    - '#b689ee'
    - '#a0e471'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.8603894533589482
purpose: []
