layout_spectrum: 0.26277682930231094
typography_spectrum: 0.9229804375208914
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.2868903074413538
  lightness: 0.7092176261357963
  saturation: 0.19394385069608688
  rhythmicContrast: 0.919053687248379
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Core Process Psycotherapy
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Core Process
    id: 26ac9968-2783-4b91-873c-03ec3f3bec3a
    type: content
  - name: Who is psychotherapy for?
    id: 1dee3722-5e6c-4f70-8b74-76266d2c62d4
    type: content
  - name: Courses & Events
    id: 0e0a02b7-d1ec-426b-8b24-73fa385e3a78
    type: content
  - name: Contact
    id: c2626c16-239f-44b4-9f12-9ef6c98a8dd0
    type: content
  - name: In crisis?
    id: 36271eec-6bc7-4c96-a0df-54587e110544
    type: content
favicon: null
title: ''
description: ''
purpose: []
